'use client'

import { useState, useEffect, useCallback } from 'react'
import { FileText, Download, Eye, RefreshCw } from 'lucide-react'
import { cn, formatRelativeTime } from '@/lib/utils'

interface ProposalAsset {
  id: string
  type: string
  name: string
  description: string | null
  filePath: string | null
  url: string | null
  status: string
  createdAt: string
  business: { id: string; name: string } | null
}

export default function PitchDecksPage() {
  const [decks, setDecks] = useState<ProposalAsset[]>([])
  const [loading, setLoading] = useState(true)

  const fetchDecks = useCallback(async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/businesses?limit=200')
      if (res.ok) {
        const data = await res.json()
        const allAssets: ProposalAsset[] = []
        for (const business of data.businesses) {
          if (business._count?.generatedAssets > 0) {
            const detailRes = await fetch(`/api/businesses/${business.id}`)
            if (detailRes.ok) {
              const detail = await detailRes.json()
              if (detail.generatedAssets) {
                detail.generatedAssets.forEach((a: ProposalAsset) => {
                  allAssets.push({ ...a, business: { id: business.id, name: business.name } })
                })
              }
            }
          }
        }
        setDecks(allAssets.filter(a => a.type === 'pitch_deck' || a.type === 'proposal'))
      }
    } catch (err) {
      console.error('Failed to fetch pitch decks', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    // fetchDecks sets loading=true internally, this is a false positive for react-hooks/set-state-in-effect
    // eslint-disable-next-line react-hooks/exhaustive-deps
    fetchDecks()
  }, [fetchDecks])

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-text-primary">Pitch Decks</h1>
          <p className="text-sm text-text-muted mt-0.5">Generated pitch decks and proposals</p>
        </div>
        <button onClick={fetchDecks} className="btn-ghost btn-sm">
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="card animate-pulse space-y-3">
              <div className="skeleton h-5 w-40" />
              <div className="skeleton h-3 w-28" />
              <div className="flex gap-2 mt-4">
                <div className="skeleton h-8 w-20 rounded-lg" />
                <div className="skeleton h-8 w-20 rounded-lg" />
              </div>
            </div>
          ))}
        </div>
      ) : decks.length === 0 ? (
        <div className="card py-16 text-center">
          <FileText className="w-12 h-12 text-text-muted/30 mx-auto mb-3" />
          <p className="text-sm text-text-muted">No pitch decks generated yet</p>
          <p className="text-xs text-text-muted/60 mt-1">Pitch decks will appear here once generated by agents</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {decks.map((deck) => (
            <div key={deck.id} className="card hover:border-border-light transition-all duration-200">
              <div className="flex items-start justify-between mb-3">
                <div>
                  <h3 className="text-sm font-semibold text-text-primary">{deck.name}</h3>
                  {deck.business && (
                    <p className="text-xs text-text-muted mt-0.5">{deck.business.name}</p>
                  )}
                </div>
                <span className={cn(
                  'badge text-[10px]',
                  deck.status === 'approved' ? 'badge-green' : 'badge-blue'
                )}>
                  {deck.status}
                </span>
              </div>

              {deck.description && (
                <p className="text-xs text-text-secondary mb-3 line-clamp-2">{deck.description}</p>
              )}

              <div className="text-[10px] text-text-muted mb-3">
                Generated {formatRelativeTime(deck.createdAt)}
              </div>

              <div className="flex items-center gap-2">
                <button className="btn-sm btn-primary">
                  <Eye className="w-3 h-3" />
                  Preview
                </button>
                <button className="btn-sm btn-secondary">
                  <Download className="w-3 h-3" />
                  Export PDF
                </button>
                <button className="btn-sm btn-ghost ml-auto">
                  <RefreshCw className="w-3 h-3" />
                  Regenerate
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}