'use client'

import { useState, useEffect, useCallback } from 'react'
import { Globe, ExternalLink, FolderOpen, RefreshCw, Eye } from 'lucide-react'
import { cn, formatDate, formatRelativeTime } from '@/lib/utils'

interface Asset {
  id: string
  type: string
  name: string
  description: string | null
  filePath: string | null
  url: string | null
  status: string
  approvedAt: string | null
  createdAt: string
  business: { id: string; name: string } | null
}

export default function WebsitesPage() {
  const [assets, setAssets] = useState<Asset[]>([])
  const [loading, setLoading] = useState(true)

  const fetchAssets = useCallback(async () => {
    try {
      const res = await fetch('/api/businesses?limit=200')
      if (res.ok) {
        const data = await res.json()
        const allAssets: Asset[] = []
        for (const business of data.businesses) {
          if (business._count?.generatedAssets > 0) {
            const detailRes = await fetch(`/api/businesses/${business.id}`)
            if (detailRes.ok) {
              const detail = await detailRes.json()
              if (detail.generatedAssets) {
                detail.generatedAssets.forEach((a: Asset) => {
                  allAssets.push({ ...a, business: { id: business.id, name: business.name } })
                })
              }
            }
          }
        }
        setAssets(allAssets.filter(a => a.type === 'website'))
      }
    } catch (err) {
      console.error('Failed to fetch websites', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchAssets()
  }, [fetchAssets])

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-text-primary">Website Generator</h1>
          <p className="text-sm text-text-muted mt-0.5">Generated websites and their status</p>
        </div>
        <button onClick={fetchAssets} className="btn-ghost btn-sm">
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="card animate-pulse space-y-3">
              <div className="skeleton h-5 w-32" />
              <div className="skeleton h-3 w-24" />
              <div className="skeleton h-8 w-full rounded-lg" />
            </div>
          ))}
        </div>
      ) : assets.length === 0 ? (
        <div className="card py-16 text-center">
          <Globe className="w-12 h-12 text-text-muted/30 mx-auto mb-3" />
          <p className="text-sm text-text-muted">No websites generated yet</p>
          <p className="text-xs text-text-muted/60 mt-1">Websites will appear here once generated by agents</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {assets.map((asset) => (
            <div key={asset.id} className="card hover:border-border-light transition-all duration-200">
              <div className="flex items-start justify-between mb-3">
                <div>
                  <h3 className="text-sm font-semibold text-text-primary">{asset.name}</h3>
                  {asset.business && (
                    <p className="text-xs text-text-muted mt-0.5">{asset.business.name}</p>
                  )}
                </div>
                <span className={cn(
                  'badge text-[10px]',
                  asset.status === 'approved' ? 'badge-green' :
                  asset.status === 'archived' ? 'badge-gray' :
                  asset.status === 'generated' ? 'badge-blue' : 'badge-yellow'
                )}>
                  {asset.status}
                </span>
              </div>

              {asset.description && (
                <p className="text-xs text-text-secondary mb-3 line-clamp-2">{asset.description}</p>
              )}

              <div className="flex items-center gap-2 text-[10px] text-text-muted mb-3">
                <span>{formatRelativeTime(asset.createdAt)}</span>
                {asset.approvedAt && <span>· Approved {formatDate(asset.approvedAt)}</span>}
              </div>

              <div className="flex items-center gap-2">
                {asset.url && (
                  <a href={asset.url} target="_blank" rel="noopener noreferrer" className="btn-sm btn-primary">
                    <Eye className="w-3 h-3" />
                    Preview
                  </a>
                )}
                <button className="btn-sm btn-ghost">
                  <FolderOpen className="w-3 h-3" />
                  Open Folder
                </button>
                <button className="btn-sm btn-ghost ml-auto">
                  <RefreshCw className="w-3 h-3" />
                  Regenerate
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}